# Generated by Django 4.2.7 on 2025-11-11 05:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('autor', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('libro', 'Libro'), ('revista', 'Revista'), ('articulo', 'Artículo'), ('tesis', 'Tesis'), ('ebook', 'Libro Digital'), ('revista_digital', 'Revista Digital'), ('video', 'Video'), ('audio', 'Audio')], max_length=20)),
                ('formato', models.CharField(choices=[('fisico', 'Físico'), ('digital', 'Digital')], default='fisico', max_length=10)),
                ('isbn', models.CharField(blank=True, help_text='ISBN-10 o ISBN-13', max_length=17, null=True, unique=True)),
                ('codigo_interno', models.CharField(max_length=20, unique=True)),
                ('editorial', models.CharField(blank=True, max_length=150)),
                ('anio_publicacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2100)])),
                ('edicion', models.CharField(blank=True, max_length=50)),
                ('idioma', models.CharField(default='Español', max_length=50)),
                ('categoria', models.CharField(max_length=100)),
                ('palabras_clave', models.CharField(blank=True, help_text='Separadas por comas', max_length=300)),
                ('materia', models.CharField(blank=True, max_length=100)),
                ('ubicacion', models.CharField(blank=True, help_text='Ej: Estante A3, Nivel 2', max_length=50)),
                ('numero_copias', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('copias_disponibles', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('url_acceso', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('archivo', models.FileField(blank=True, null=True, upload_to='recursos_digitales/')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('reservado', 'Reservado'), ('mantenimiento', 'Mantenimiento'), ('extraviado', 'Extraviado'), ('baja', 'Dado de Baja')], default='disponible', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('resumen', models.TextField(blank=True)),
                ('paginas', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('veces_prestado', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
