# Generated by Django 4.2.7 on 2025-11-11 05:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('estudiante', 'Estudiante'), ('docente', 'Docente'), ('bibliotecario', 'Bibliotecario'), ('administrador', 'Administrador')], default='estudiante', max_length=20)),
                ('codigo_universitario', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8,12}$', 'Código debe tener entre 8 y 12 dígitos')])),
                ('programa_academico', models.CharField(blank=True, max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('direccion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('prestamos_permitidos', models.IntegerField(default=3)),
                ('sancionado', models.BooleanField(default=False)),
                ('fecha_fin_sancion', models.DateField(blank=True, null=True)),
                ('motivo_sancion', models.TextField(blank=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
